#pragma once

#include <windows.h>

#include "board/io4.h"

HRESULT mai2_io4_hook_init(const struct io4_config *cfg);

enum {
    MAI2_GPIO_1P_READER_LED = 0x2000,
    MAI2_GPIO_ALLOW_COIN = 0x4000,
    MAI2_GPIO_2P_READER_LED = 0x0400,
    MAI2_GPIO_CAMERA_RING_LED = 0x0080,
    MAI2_GPIO_CAMERA_RECORDING_LED = 0x0040,
};

enum {
    MAI2_UNIQUE1_1P_BILLBOARD_LED_R_OFFSET = 2,
    MAI2_UNIQUE1_1P_BILLBOARD_LED_G_OFFSET = 4,
    MAI2_UNIQUE1_1P_BILLBOARD_LED_B_OFFSET = 6,
    MAI2_UNIQUE1_2P_BILLBOARD_LED_R_OFFSET = 3,
    MAI2_UNIQUE1_2P_BILLBOARD_LED_G_OFFSET = 5,
    MAI2_UNIQUE1_2P_BILLBOARD_LED_B_OFFSET = 7,
};
